apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: time-check
  name: time-check
  namespace: dv
spec:
  containers:
  - image: busybox
    name: time-check
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
