apiVersion: v1
kind: Service
metadata:
  annotations:
    meta.helm.sh/release-name: mysql-1679646754
    meta.helm.sh/release-namespace: default
  creationTimestamp: "2023-03-24T08:32:35Z"
  labels:
    app.kubernetes.io/component: primary
    app.kubernetes.io/instance: mysql-1679646754
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: mysql
    helm.sh/chart: mysql-9.7.0
  name: mysql-1679646754
  namespace: default
  resourceVersion: "90568"
  uid: f3c42eec-293c-41b7-a911-3507f97802cc
spec:
  clusterIP: 10.107.65.33
  clusterIPs:
  - 10.107.65.33
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: mysql
    nodePort: 30765
    port: 3306
    protocol: TCP
    targetPort: mysql
  selector:
    app.kubernetes.io/component: primary
    app.kubernetes.io/instance: mysql-1679646754
    app.kubernetes.io/name: mysql
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
