apiVersion: v1
kind: Service
metadata:
  annotations:
    meta.helm.sh/release-name: mysql-1679646754
    meta.helm.sh/release-namespace: default
  creationTimestamp: "2023-03-24T08:32:35Z"
  labels:
    app.kubernetes.io/component: primary
    app.kubernetes.io/instance: mysql-1679646754
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: mysql
    helm.sh/chart: mysql-9.7.0
  name: mysql-1679646754-headless
  namespace: default
  resourceVersion: "30862"
  uid: 5f83b194-4c6c-42d6-9b79-fd9373678d51
spec:
  clusterIP: None
  clusterIPs:
  - None
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: mysql
    port: 3306
    protocol: TCP
    targetPort: mysql
  publishNotReadyAddresses: true
  selector:
    app.kubernetes.io/component: primary
    app.kubernetes.io/instance: mysql-1679646754
    app.kubernetes.io/name: mysql
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
