apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    app: test
  name: pod-test
spec:
  containers:
  - image: nginx
    name: pod-test
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
