apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    app: data
  name: pod-test
  namespace: container-name
spec:
  containers:
  - image: busybox
    name: pod-test
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
