apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2023-03-23T07:36:31Z"
  labels:
    app: kbae
  name: service-test
  namespace: default
  resourceVersion: "10175"
  uid: 1a71236d-7c3c-4de0-86a3-910882680504
spec:
  clusterIP: 10.111.228.172
  clusterIPs:
  - 10.111.228.172
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 30970
    port: 32000
    protocol: TCP
    targetPort: 32000
  selector:
    app: kbae
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
