apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: multi-pod
  name: multi-pod
spec:
  containers:
  - image: nginx
    name: jupiter
    env:
    - name: type
      value: planet
  - image: busybox
    name: europa
    command: ["/bin/sh","-c","sleep 4800"]  # ""은 명령어 단위. "while true; do echo hello; sleep 10;done" 처럼 붙여 쓴다.
    env:
     - name: type
       value: moon