apiVersion: v1
kind: Pod
metadata:
  labels:
    run: my-busybox
  name: my-busybox
  namespace: dev2406
spec:
  containers:
    - image: busybox
      imagePullPolicy: Always
      name: secret
      resources: {}
      terminationMessagePath: /dev/termination-log
      terminationMessagePolicy: File
      command:
        - sleep
        - "3600"
      volumeMounts:
        - mountPath: /etc/secret-volume
          name: secret-volume
          readOnly: true
  volumes:
    - name: secret-volume
      secret:
        secretName: dotfile-secret
        optional: false # default setting; "mysecret" must exist
  nodeName: controlplane
# error
# Error from server (BadRequest): Pod in version "v1" cannot be handled as a Pod:
# json: cannot unmarshal number into Go struct field Container.spec.containers.command of type string
