apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: time-check
  name: time-check
  namespace: dvl1987
spec:
  containers:
  - command:
    - while true; do date; sleep $TIME_FREQ;done > /opt/time/time-check.log
    image: busybox
    name: time-check
    env:
        # Define the environment variable
        - name: PLAYER_INITIAL_LIVES # Notice that the case is different here
                                     # from the key name in the ConfigMap.
          valueFrom:
            configMapKeyRef:
              name: time-config           # The ConfigMap this value comes from.
              key: TIME_FREQ
    resources: {}
    volumeMounts:
    - name: redis-storage
      mountPath: /opt/time
  volumes:
  - name: redis-storage
    emptyDir: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}