# k run pod6 -n default --image nginx $do --command -- sh -c "touch /tmp/ready && sleep 1d" > 6.yaml


apiVersion: v1
kind: Pod
metadata:
  labels:
    run: pod6
  name: pod6
  namespace: default
spec:
  containers:
  - command:
    - sh
    - -c
    - touch /tmp/ready && sleep 1d
    image: busybox:1.31.0
    name: pod6
    resources: {}
    readinessProbe:
      exec:
        command:
        - cat
        - /tmp/ready
      initialDelaySeconds: 5
      periodSeconds: 10
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
