apiVersion: v1
kind: Pod
metadata:
  name: my-pod
  namespace: ckad
spec:
  containers:
  - name: my-container
    image: nginx
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 500m
        memory: 512Mi
